#!/bin/bash -ex

# https://apple.stackexchange.com/questions/266333/how-to-show-italic-in-vim-in-iterm2

printf 'xterm-256color|xterm with 256 colors and italic,\n  sitm=\\E[3m, ritm=\\E[23m,\n  use=xterm-256color,' > xterm-256color.terminfo.txt
tic -o ~/.terminfo xterm-256color.terminfo.txt
rm xterm-256color.terminfo.txt
