#!/bin/bash -ex

echo "xterm-256color|xterm with 256 colors and italic,\n" sitm=\E[3m, ritm=\E[23m,\n" use=xterm-256color," > xterm-256color.terminfo.txt
tic -o ~/.terminfo xterm-256color.terminfo.txt
rm xterm-256color.terminfo.txt
